# file: roles/openshift.prereq/tasks/rhel.yml
---

- name: Install base packages
  ansible.builtin.yum: name={{ item }} state=present
  with_items: "{{ rhel_base_pkgs }}"

- name: Update the system to the latest packages
  ansible.builtin.yum: name=* state=latest

- name: Install OpenShift packages
  ansible.builtin.yum: name={{ item }} state=present
  with_items: "{{ rhel_ose_pkgs }}"

- name: Remove atomic-openshift packages in the host’s /etc/yum.conf file when installing
  ansible.builtin.command: atomic-openshift-excluder unexclude

- name: Eanble insecure registry
  ansible.builtin.shell: sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16 --log-opt max-size=1M --log-opt max-file=3"' /etc/sysconfig/docker

- name: Prepare additional block device
  ansible.builtin.shell: echo -e "WIPE_SIGNATURES=true\nDEVS={{ os_docker_block_device }}\nVG={{ os_docker_volume_group }}" >> /etc/sysconfig/docker-storage-setup

- name: Create 'docker-pool' logical volume
  ansible.builtin.command: docker-storage-setup

- name: Start docker
  ansible.builtin.service: name=docker state=started enabled=yes

- name: get EC2 Facts
  action: ec2_facts

- ansible.builtin.debug: var=hostvars

- name: Template inventory file to host
  ansible.builtin.template: dest={{ default_home }}/inventory_ose  src=inventory_ose.j2
