# file: roles/subscription_manager/tasks/main.yml
---
# Red Hat Cloud Access
- ansible.builtin.include: cloud_access.yml

# Subscribe machines via username & password
# or activation keys
- ansible.builtin.include: subscribe.yml
