---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: "1.9.6" # note that ranges are not supported for roles


collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
    version: ">=6.3.0"
  - name: ansible.posix
  - name: azure.azcollection
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: containers.podman
  - name: kubernetes.core
