---
#---------------------------------------------------
# Cloud Access
#---------------------------------------------------
- name: Cloud Access | Enable Extras repos
  ansible.builtin.shell: yum-config-manager --enable rhui-REGION-rhel-server-extras --save
  when: cloud_access

- name: Cloud Access | Enable Optional repos
  ansible.builtin.shell: yum-config-manager --enable rhui-REGION-rhel-server-optional --save
  when: cloud_access

