---
#---------------------------------------------------
# DNS Setup
#---------------------------------------------------
#- name: Add DNS entries for subscription
#  blockinfile:
#    path: /etc/hosts
#    block: |
#      209.132.183.44   xmlrpc.rhn.redhat.com
#      23.204.148.218   content-xmlrpc.rhn.redhat.com
#      209.132.183.49   subscription.rhn.redhat.com
#      209.132.183.108  subscription.rhsm.redhat.com
#      209.132.182.63   registry.access.redhat.com
#      #209.132.182.33   repository.jboss.org
#    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
#    insertafter: EOF
#  when: not cloud_access
#  tags:
#    - rhel

#---------------------------------------------------
# Key Installation
#---------------------------------------------------
- name: Import keys (rhel 6)
#  shell: rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when: not cloud_access and ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6'
  tags:
    - rhel

- name: Import keys (rhel 7+)
  ansible.builtin.shell: rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
# DISABLED BECAUSE IT IS SLOW, ACROSS MANY NODES
#  rpm_key:
#    state: present
#    key: "{{ item }}"
#  with_items:
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when: not cloud_access and ansible_distribution == 'RedHat' and ansible_distribution_major_version > '6'
  tags:
    - rhel
#---------------------------------------------------
# Subscribe to RHN
#---------------------------------------------------
- name: Check RHN subscription status
  ansible.builtin.command: subscription-manager status
  register: sm_result
  ignore_errors: True
  tags:
    - rhel

- ansible.builtin.debug:
    var: cloud_access

- ansible.builtin.debug:
    var: rhsm_activationkey

- ansible.builtin.debug:
    var: rhsm_org_id

- ansible.builtin.debug:
    var: username

- ansible.builtin.debug:
    var: password

- ansible.builtin.debug:
    var: pool_id

- ansible.builtin.debug:
    var: cloud_access

- ansible.builtin.debug:
    var: sm_result

- name: Remove RHUI client (RHEL 8)
  ansible.builtin.package:
    name: rh-amazon-rhui-client
    state: absent
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8' and (username or rhsm_activationkey)

- name: Subscribe to RHSM via activation key / org id
  block:
    - community.general.redhat_subscription:
        activationkey: "{{ rhsm_activationkey }}"
        org_id: "{{ rhsm_org_id }}"
        force_register: true
        state: present
      register: actkey_result
  rescue:
    - name: Retrying subscription
      community.general.redhat_subscription:
        activationkey: "{{ rhsm_activationkey }}"
        org_id: "{{ rhsm_org_id }}"
        force_register: true
        state: present
      register: actkey_result
  when: sm_result.failed and not username
  tags:
    - rhel

- name: Subscribe to RHSM via username/password/pool_id
  block:
    - community.general.redhat_subscription:
        username: "{{ username }}"
        password: "{{ password }}"
        pool: "{{ pool_id }}"
        force_register: true
        state: present
  rescue:
    - name: Retrying subscription
      community.general.redhat_subscription:
        username: "{{ username }}"
        password: "{{ password }}"
        pool: "{{ pool_id }}"
        force_register: true
        state: present
  when: sm_result.failed and not rhsm_activationkey
  tags:
    - rhel

- name: Ensure RHSM manages repos
  ansible.builtin.command:
    cmd: subscription-manager config --rhsm.manage_repos=1
  when: ansible_distribution == 'RedHat' and (username or rhsm_activationkey)

#---------------------------------------------------
# Add Required Repositories
#---------------------------------------------------
- name: RHEL 8 tasks
  ansible.builtin.import_tasks: repos-rhel8.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8' and beta|default(False)==False and (username or rhsm_activationkey)

- name: RHEL 8 beta tasks
  ansible.builtin.import_tasks: repos-rhel8beta.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8' and beta|default(False)==True and (username or rhsm_activationkey)

...
