# file: roles/openshift.config/tasks/logging.yml
---

- name: Add metricsPublicURL to master-config file
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/origin/master/master-config.yaml
    insertafter: "assetConfig:"
    line:  "  loggingPublicURL: https://kibana.{{ default_wildcard }}"

- name: Restart master service
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - atomic-openshift-master-api
  - atomic-openshift-master-controllers
