---

- name: Check to see if requisite repos are already enabled (rhel 6)
  become: yes
  ansible.builtin.shell: subscription-manager repos --list-enabled | egrep 'rhel-6-server-extras-rpms|rhel-6-server-optional-rpms|rhel-6-server-rpms|jb-eap-7.1-for-rhel-6-server-rpms|rhel-server-rhscl-6-rpms' | wc -l
  register: smr_result
  ignore_errors: True
  tags:
    - rhel

- name: Disable all repos by default (rhel 6)
  ansible.builtin.command: subscription-manager repos --disable "*"
  when: smr_result.stdout != "5"
  tags:
    - rhel

- name: Enable the requisite repos (rhel 6)
  ansible.builtin.shell: subscription-manager repos --enable="rhel-6-server-rpms" --enable="rhel-6-server-extras-rpms" --enable="rhel-6-server-optional-rpms" --enable="jb-eap-7.1-for-rhel-6-server-rpms" --enable="rhel-server-rhscl-6-rpms" #--enable="rhel-7-server-ose-3.4-rpms"
  when: smr_result.stdout != "5"
  tags:
    - rhel

...
