#--------------------------------------------------
# Install Ansible
#--------------------------------------------------

- name: Install base packages
  become: yes
  ansible.builtin.yum:
    name:
      - vim
      - git
      - ansible
      - nano
    state: latest
    enablerepo: epel-testing
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- block:
  - name: Determine newest Ansible repo
    ansible.builtin.shell: "subscription-manager repos --list | egrep '^Repo ID:' | egrep 'ansible.*64-rpms' | sort -V -k3 | sed 's/.* //' | tail -1 "
    register: result

  - ansible.builtin.debug:
      msg: "{{ result.stdout_lines }}"

  - ansible.builtin.set_fact: 
      ansible_repo: "{{ result.stdout }}"

  # ansible has migrated to epel
#  - name: Enable Ansible repo
#    rhsm_repository:
#      name: "{{ ansible_repo }}"
#    when: not beta|default(False)

  - name: Install base packages
    become: yes
    ansible.builtin.yum:
      name:
        - vim
        - git
        - ansible
        - nano
      state: latest

  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name: Fake, if missing, the dbus-1 directory
  ansible.builtin.file:
    path: /usr/lib64/dbus-1
    state: directory

- name: Fake, if missing, the dbus dbus-daemon-launch-helper file
  ansible.builtin.file:
    path: /usr/lib64/dbus-1/dbus-daemon-launch-helper
    state: touch

- name: Install vimrc in home directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ system_user }}/{{ item.dest }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  with_items:
    - { src: "vimrc", dest: ".vimrc" }

- name: Copy over SSH Key to {{ system_user }} home
  ansible.builtin.copy: 
    src: "{{ ssh_key_path }}"
    dest: "/home/{{ system_user }}/.ssh/{{ workshop_prefix }}-tower" 
    mode: 0400 
    group: "{{ system_user }}"
    owner: "{{ system_user }}"

- name: Template over ansible.cfg
  ansible.builtin.template:
    dest: "/home/{{ system_user }}/.ansible.cfg"
    src: "ansible.cfg.j2"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
