#--------------------------------------------------
# Install Ansible
#--------------------------------------------------

- name: Install base packages
  become: yes
  yum:
    name:
      - vim
      - git
      - ansible
      - nano
    state: latest
    enablerepo: epel-testing
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- block:
  - name: Determine newest Ansible repo
    shell: "subscription-manager repos --list | awk 'BEGIN{repo=""} $0 ~ /^Repo ID:/ && $NF ~ /ansible.*[0-9]-rpms/ && $NF !~ /ansible-2\.[0-9]/ && $NF !~ /debug/ && $NF !~ /rhui/ && $NF !~ /ansible-automation-platform/ {if($NF > repo) repo=$NF} END{print repo}' "
    register: result

  - debug:
      msg: "{{ result.stdout_lines }}"

  - set_fact: 
      ansible_repo: "{{ result.stdout }}"

  # ansible has migrated to epel
#  - name: Enable Ansible repo
#    rhsm_repository:
#      name: "{{ ansible_repo }}"
#    when: not beta|default(False)

  - name: Install base packages
    become: yes
    yum:
      name:
        - vim
        - git
        - ansible
        - nano
      state: latest

  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name: Fake, if missing, the dbus-1 directory
  file:
    path: /usr/lib64/dbus-1
    state: directory

- name: Fake, if missing, the dbus dbus-daemon-launch-helper file
  file:
    path: /usr/lib64/dbus-1/dbus-daemon-launch-helper
    state: touch

- name: Install vimrc in home directory
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ system_user }}/{{ item.dest }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  with_items:
    - { src: "vimrc", dest: ".vimrc" }

- name: Copy over SSH Key to {{ system_user }} home
  copy: 
    src: "{{ ssh_key_path }}"
    dest: "/home/{{ system_user }}/.ssh/{{ workshop_prefix }}-tower" 
    mode: 0400 
    group: "{{ system_user }}"
    owner: "{{ system_user }}"

- name: Template over ansible.cfg
  template:
    dest: "/home/{{ system_user }}/.ansible.cfg"
    src: "ansible.cfg.j2"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
