# file: roles/unregister/tasks/main.yml
---

#---------------------------------------------------
# Unsubscribe from RHN
#---------------------------------------------------

# - name: Check RHN subscription status
#   command: subscription-manager status
#   register: sm_result
#   ignore_errors: True

- block:
#  - name: Check to see if the host still exists
#    command: "host {{ item }}"
#    with_items: rhel_nodes
#    register: results

  - name: Unsubscribe RHN
    community.general.redhat_subscription:
      state: absent
    when: not cloud_access
#    when: not cloud_access and not results.failed

  ignore_errors: true
  ignore_unreachable: true
