# file: roles/openshift.config/tasks/acct.yml
---

- name: Create admin account
  become: yes
  community.general.htpasswd:
    name: '{{ openshift_cluster_admin_username }}'
    password: '{{ openshift_cluster_admin_password }}'
    path: "/etc/origin/master/htpasswd"
    state: present

- name: Add cluster role to admin account
  ansible.builtin.shell: oc adm --config=/etc/origin/master/admin.kubeconfig policy add-cluster-role-to-user cluster-admin {{ openshift_cluster_admin_username }}

- name: Create users for OpenShift web interface
  ansible.builtin.shell: htpasswd -b /etc/origin/master/htpasswd user{{ item }} {{ openshift_test_users_password }}
  with_sequence: count={{ openshift_test_users_count }}

- name: Create users for shell/OC client access
  ansible.builtin.user:
    name:      "user{{ item }}"
    password:  "{{ workshop_password |password_hash('sha512') }}"
    state:     present
  with_sequence: count={{ openshift_test_users_count }}
