---
#--------------------------------------------------
# Install Tower
#--------------------------------------------------
- name: Download Latest Tower packge
  become: yes
  ansible.builtin.get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz dest=/tmp/ansible-tower-setup-latest.tar.gz   validate_certs=false 

- name: Unarchive Tower Package
  become: yes
  ansible.builtin.unarchive: dest=/tmp/ src=/tmp/ansible-tower-setup-latest.tar.gz 

- name: Remove download ansible-tower-setup-latest.tar.gz
  become: yes
  ansible.builtin.command: rm ansible-tower-setup-latest.tar.gz chdir=/tmp/

- name: Rename dir
  become: yes
  ansible.builtin.shell: mv ansible-tower-setup-* ansible-tower-setup chdir=/tmp/    

- name: Template over Ansible Inventory to setup
  become: yes
  ansible.builtin.template: dest=/tmp/ansible-tower-setup/inventory  src=inventory.j2

- name: Install Tower
  become: yes
  become_user: root
  ansible.builtin.command: ./setup.sh chdir=/tmp/ansible-tower-setup  

#--------------------------------------------------
# Install tower-cli
#--------------------------------------------------
- name: Install pip
  become: yes
  become_user: root
  ansible.builtin.yum: name=python-pip  state=present

- name: Install tower-cli
  become: yes
  become_user: root
  ansible.builtin.pip: name=ansible-tower-cli state=present

#--------------------------------------------------
# Add License
#--------------------------------------------------
- name: Add Ansible Tower License
  become: yes
  become_user: root
  ansible.builtin.copy: src=license dest=/etc/tower/license

