python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
colors elflord
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
set laststatus=2 tabstop=2 shiftwidth=2 expandtab
syntax on
