---

- name: Disable rhui plugins
  ansible.builtin.lineinfile: dest={{ item }} regexp='^enabled' line='enabled=0' state=present
  become: true
  with_items:
   - /etc/yum/pluginconf.d/amazon-id.conf
   - /etc/yum/pluginconf.d/rhui-lb.conf

- name: Disable rhui repos
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: 'enabled=1'
    replace: 'enabled=0'
  become: true
  with_items:
   - /etc/yum.repos.d/redhat-rhui.repo
   - /etc/yum.repos.d/redhat-rhui-client-config.repo

- name: Enable rhsm plugins
  ansible.builtin.lineinfile: dest={{ item }} regexp='^enabled' line='enabled=1' state=present
  become: true
  with_items:
    - /etc/yum/pluginconf.d/product-id.conf
    - /etc/yum/pluginconf.d/subscription-manager.conf

- name: Add dns entries
  ansible.builtin.blockinfile:
   path: /etc/hosts
   block: |
    209.132.183.44   xmlrpc.rhn.redhat.com
    23.204.148.218   content-xmlrpc.rhn.redhat.com
    209.132.183.49   subscription.rhn.redhat.com
    209.132.183.108  subscription.rhsm.redhat.com
    209.132.182.63   registry.access.redhat.com
    209.132.182.33   repository.jboss.org
  marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  insertafter: EOF
  become: true

#---------------------------------------------------
# Red Hat Product Signing (GPG) Keys
# See https://access.redhat.com/security/team/key
#---------------------------------------------------

- name: Import package-signing keys
  ansible.builtin.shell: /usr/bin/rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  become: true

#---------------------------------------------------
# Red Hat Subscription Management (RHSM)
# See https://access.redhat.com/
#---------------------------------------------------

- name: Force unregister before
  community.general.redhat_subscription:
   state: absent
  ignore_errors: true
  become: true

- name: Customer portal registration
  community.general.redhat_subscription:
   state: present
   username: "{{ rhsm_user_name }}"
   password: "{{ rhsm_user_pass }}"
   autosubscribe: false
  register: result
  until: result | succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_user_name is defined) and
        (rhsm_user_pass is defined)

- name: Activation key registration
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key_id }}"
    org_id: "{{ rhsm_org_id }}"
    autosubscribe: false
  register: result
  until: result | succeeded
  retries: 10
  delay: 5
  become: true
  when: (rhsm_key_id is defined) and
        (rhsm_org_id is defined)

- name: Subscribe pool id
  ansible.builtin.shell: /usr/bin/subscription-manager attach --pool={{ rhsm_pool_id }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5
  ignore_errors: no
  become: true
  when: rhsm_pool_id is defined

- name: Disable all rhsm repos
  ansible.builtin.shell: /usr/bin/subscription-manager repos --disable="*"
  retries: 5
  delay: 10
  become: true

- name: Disable all yum repos
  ansible.builtin.shell: /usr/bin/yum-config-manager --disable \*
  become: true

- name: Enable baseline repos
  ansible.builtin.shell: /usr/bin/subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"
  retries: 5
  delay: 10
  become: true

- name: Upgrade packages
  ansible.builtin.yum: name=* state=latest
  become: true
