#--------------------------------------------------
# Install Ansible
#--------------------------------------------------

- name: Install base packages
  become: yes
  ansible.builtin.yum: name={{ item }} state=latest enablerepo=epel-testing
  with_items: 
      - vim
      - git
      - ansible
      - nano
  when: install

- name: Fake, if missing, the dbus-1 directory
  ansible.builtin.file:
    path: /usr/lib64/dbus-1
    state: directory

- name: Fake, if missing, the dbus dbus-daemon-launch-helper file
  ansible.builtin.file:
    path: /usr/lib64/dbus-1/dbus-daemon-launch-helper
    state: touch

- name: Install ansible.cfg and vimrc in home directory
  ansible.builtin.copy:
    src="{{ item.src }}"
    dest="/home/{{ system_user }}/{{ item.dest }}"
    owner="{{ system_user }}"
    group="{{ system_user }}"
  with_items:
    - { src: "vimrc", dest: ".vimrc" }
    - { src: "license", dest: "license" }
  when: install

- name: Copy over SSH Key to {{ system_user }} home
  ansible.builtin.copy: 
    src: "{{ terraform_working_dir }}/{{ workshop_prefix }}-tower" 
    dest: "/home/{{ system_user }}/.ssh/{{ workshop_prefix }}-tower" 
    mode: 0400 
    group: "{{ system_user }}"
    owner: "{{ system_user }}"
  when: install

- name: Template over ansible.cfg
  ansible.builtin.template:
    dest="/home/{{ system_user }}/ansible.cfg"
    src=ansible.cfg.j2  
    owner="{{ system_user }}"
    group="{{ system_user }}"
  when: install
