---
# tasks file for cockpit
- name: Install cockpit
  block:
  - name: Ensure cockpit packages exist
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    with_items:
    - cockpit
    - cockpit-dashboard
    - cockpit-shell
    - cockpit-ws
    - cockpit-doc
    - cockpit-docker
    - rsync
    - vim
    - wget

  - name: Ensure cockpit is started
    ansible.builtin.service:
      name: cockpit.socket
      state: started
      enabled: yes

