# file: 2_load.yml
---
# https://www.terraform.io/docs/providers/azurerm

- name: Wait for Azure VM's to become initialized
  hosts: localhost
  tasks:
    - ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items: "{{ groups.all_nodes }}"

- name: Configure repositories on all nodes
  become: yes
  remote_user: azure-user
  hosts: tower_nodes
  roles:
    - { role: subscription_manager }
    - { role: epel }
    - { role: upgrade }

- name: Configure repositories on tower nodes
  become: yes
  remote_user: azure-user
  hosts: nodes
  roles:
    - { role: subscription_manager }
    - { role: upgrade }

- name: Do generic configuration
  become: yes
  remote_user: azure-user
  hosts: all_nodes
  tasks:
  - name: Remove default JBoss packages
    ansible.builtin.package:
      name: eap7-*
      state: absent

- name: Configure firewalls on nodes
  become: yes
  remote_user: azure-user
  hosts: all_nodes
  roles:
    - { role: firewall }

- name: Configure repositories on nodes
  become: yes
  remote_user: azure-user
  hosts: le_node
  roles:
    - { role: LetsEncrypt }

- name: Configure software on nodes
  become: yes
  remote_user: azure-user
  hosts: tower_nodes
  roles:
    - { role: nodejs }
    - { role: wetty }
    - { role: zsh }
    - { role: codiad }

- name: Prep walkthroughs for deployment
  become: yes
  remote_user: azure-user
  hosts: tower_nodes
  vars:
    install: no
    prep: yes
  roles:
    - { role: ansible.tower }

- name: Configure software and deploy walkthroughs
  become: yes
  remote_user: azure-user
  hosts: tower_nodes
  vars:
    install: yes
    prep: no
  roles:
    - { role: ansible.tower }

# {{workshop_prefix}}.tower.<student number>.redhatgov.io:8888
# Username: azure-user
# Password: redhat!@#
