---

- name: Copy application WAR file to host
  ansible.builtin.copy: src=../files/jboss-helloworld.war dest=/tmp

- name: Deploy HelloWorld to JBoss
  community.general.jboss: deploy_path=/usr/share/jboss-as/standalone/deployments/ src=/tmp/jboss-helloworld.war deployment=helloworld.war state=present
  become: true
