---
# tasks file for roles/scan-ebs

#===============================================================================
#  Search and record IDs
#===============================================================================

- name: Announce days setting
  ansible.builtin.debug:
    msg: "[ {{ ec2_region }} ] Scanning for running EBS volumes up for {{ days }} or more days."
  when: days

- name: Announce unattached setting
  ansible.builtin.debug:
    msg: "[ {{ ec2_region }} ] Scanning for unattached EBS volumes."
  when: unattached

- name: Announce mail setting
  ansible.builtin.debug:
    msg: "Sending email with the results."
  when: mail

- name: Announce stop setting
  ansible.builtin.debug:
    msg: "Stopping unattached EBS volumes."
  when: stop and unattached

- name: Initialize an empty list for our strings
  ansible.builtin.set_fact:
    unattached_html_dest: "{{ deploy_working_dir }}/unattached_vols-{{ ec2_region }}.html"
    unattached_text_dest: "{{ deploy_working_dir }}/unattached_vols-{{ ec2_region }}"
    unattached_csv_dest: "{{ deploy_working_dir }}/unattached_vols-{{ ec2_region }}.csv"
    unattached_vol_ids: []
    vol_ids: []

- name: lookup EBS volumes
  ec2_vol_facts:
    region: "{{ ec2_region }}"
  register: ec2

- name: Append unattached volume ids to a list
  ansible.builtin.set_fact:
    unattached_vol_ids: "{{ unattached_vol_ids }} + [ '{{ item.id }}' ]"
  when: item.status == 'available'
  with_items: "{{ ec2.volumes }}"
  no_log: True

#- name: Append vol ids to list if the vol is older than {{ days }}
#  set_fact:
#    vol_ids: "{{ vol_ids }} + [ '{{ item.id }}' ]"
#  when: "(ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S') - item.create_time[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')).days > days"
#  with_items: "{{ ec2.volumes }}"
#  no_log: True

#- debug:
#    var: ec2

#- debug:
#    var: unattached_vol_ids
#
- name: Make deployment working directory
  ansible.builtin.file:
    path: "{{ deploy_working_dir }}"
    state: directory

- name: Text unattached vol report
  ansible.builtin.template:
    src: "vols.j2"
    dest: "{{ unattached_text_dest }}"

- name: HTML instance report
  ansible.builtin.template:
    src: "vols-html.j2"
    dest: "{{ unattached_html_dest }}"

- name: CSV instance report
  ansible.builtin.template:
    src: "vols-csv.j2"
    dest: "{{ unattached_csv_dest }}"

- ansible.builtin.debug:
    msg: "There are {{ unattached_vol_ids|length }} unattached EBS volumes."

- name: Send e-mail
  community.general.mail:
    host: localhost
    port: 25
    to: "{{ email }}"
    subject: "AWS EC2 {{ ec2_region }}: Unattached EBS Volumes"
    body: "<pre>{{ lookup('file', unattached_html_dest ) }}</pre>"
    attach: "{{ unattached_csv_dest }}"
    subtype: "html"
  when: mail and unattached_vol_ids|length > 0

- name: Remove unattached EBS volumes
  ec2:
    state: 'absent'
    instance_ids: "{{ unattached_vol_ids }}"
  when: stop and unattached_vol_ids|length > 0

...
