# file: roles/unregister/tasks/main.yml
---

#---------------------------------------------------
# Unsubscribe from RHN
#---------------------------------------------------

# - name: Check RHN subscription status
#   command: subscription-manager status
#   register: sm_result
#   ignore_errors: True

- name: Unsubscribe RHN
  community.general.redhat_subscription:
      state: absent
  when: not cloud_access

